### PR TITLE
Fix/cors_proxy

### PR DESCRIPTION
**Pull request by SepidehAlassi**
switch to another cors proxy

### CODE REVIEW

**Comment by mdelez** [comment]
@SepidehAlassi just for my information, why do we need to change the proxy server?

**Comment by SepidehAlassi** [comment]
> @SepidehAlassi just for my information, why do we need to change the proxy server?

@mdelez 

the other one we were using (cors.bridged) has decided to ask for registration of servers using their services. They also have decided to block the requests for big files. They have already blocked our server, so our requests to fetch content from the Newton Project portal regardless of the file size are declined until we register. see an example here:

https://beol.dasch.swiss/newtonLetter/http:%2F%2Frdfh.ch%2F0801%2F-I3OIRJOR4ajH1llCz9elw

cors.bridged seems to be unstable overall.

**Review by mdelez — APPROVED** [review]

**Comment by mdelez** [comment]
> > @SepidehAlassi just for my information, why do we need to change the proxy server?
> 
> @mdelez
> 
> the other one we were using (cors.bridged) has decided to ask for registration of servers using their services. They also have decided to block the requests for big files. They have already blocked our server, so our requests to fetch content from the Newton Project portal regardless of the file size are declined until we register. see an example here:
> 
> https://beol.dasch.swiss/newtonLetter/http:%2F%2Frdfh.ch%2F0801%2F-I3OIRJOR4ajH1llCz9elw
> 
> cors.bridged seems to be unstable overall.

Thank you!

**Comment by SepidehAlassi** [comment]
@mdelez thanks for reviewing this.

**Comment by mdelez** [comment]
@SepidehAlassi you're welcome!

**Pull request merged**
