### PR TITLE
Adapt list value component

### PR DESCRIPTION
**Pull request by tobiasschweizer**
This PR adapts the list value component so it gets the labels from `ListCacheService`.

This PR cannot be merged until we can use an updated version of Knora-ui containing `ListCacheService`.

`.travis.yml` temporarily uses yalc to run the tests.

### CODE REVIEW

**Comment by flavens** [comment]
travis.yml config

```
dist: xenial
sudo: required

services:
    - docker

language: node_js

node_js:
  - "11"

cache:
  yarn: true
  directories:
  - node_modules

addons:
  chrome: stable

install: 
  - yarn global add @angular/cli
  - yarn global add yalc
  - cd ~ && git clone -b wip/upgrade-to-angular7 https://github.com/dhlab-basel/Knora-ui.git && cd Knora-ui && yarn install --prod=false && yarn build-lib-prod && yarn yalc-publish
  - cd $TRAVIS_BUILD_DIR

script:
  - yalc remove --all && yarn yalc-add-modules
  - yarn install --prod=false
  - yarn test-ci
  - docker build .
```

**Comment by tobiasschweizer** [comment]
@SepidehAlassi This PR adapts beol so it gets list nodes using Knora's list route (subject index).

**Comment by SepidehAlassi** [comment]
@tobiasschweizer should I review this?

**Comment by tobiasschweizer** [comment]
> should I review this?

We have to wait for the new Knora-ui modules to be provided by @flavens and @kilchenmann

**Comment by SepidehAlassi** [comment]
@tobiasschweizer knora-ui v.7.6.0 is available which works with Knora. v.7.0.0 Isn't the search for list nodes already a feature of Knora v.7.0.0?

**Comment by tobiasschweizer** [comment]
> knora-ui v.7.6.0 is available which works with Knora. v.7.0.0 Isn't the search for list nodes already a feature of Knora v.7.0.0?

The problem is the way the list values are represented in v2 complex. There used to be the label's node name, but now there is just the IRI.

**Comment by flavens** [comment]
@tobiasschweizer where can I get the BEOL data?

**Review by SepidehAlassi — APPROVED** [review]

**Review by flavens — APPROVED** [review]

**Comment by tobiasschweizer** [comment]
Thanks!

**Pull request merged**
