### PR TITLE
Use property's label to display a URI

### PR DESCRIPTION
**Pull request by tobiasschweizer**
https://dasch.myjetbrains.com/youtrack/issue/DSP-631

This PR adds the property labels to the uri-values so URIs are display using the label.

### CODE REVIEW

**Comment by SepidehAlassi** [comment]
@tobiasschweizer I will review this PR today

**Comment by tobiasschweizer** [comment]
> @tobiasschweizer I will review this PR today

Ok, thanks. If you need the BEOL data, let me know.

**Comment by SepidehAlassi** [comment]
> Ok, thanks. If you need the BEOL data, let me know.

I have some data from one of the last releases, I will try with that.

**Review by SepidehAlassi — APPROVED** [review]

**Comment by tobiasschweizer** [comment]
Thanks for the review. Shall I make a new release for the beol app after merging or have you spotted anything that should be fixed before deploying on the test server?

**Pull request merged**
