### PR TITLE
Wip/use knoraui viewer module

### LINKED ISSUE #39: Properties handling in template ("neededProps")
- [x] refactor mapping of properties to an interface/class to be used inside a template
- [ ] use cardinalities from the ontology

### LINKED ISSUE #40: Take properties from @knora/viewer
Remove generic property components and import the ones from @knora/viewer.
Keep property components that are Beol specific.

### LINKED ISSUE #41: Make incoming links clickable in resource template
incoming links should be rendered with Readlinkvalue component in the resource template.

### PR DESCRIPTION
**Pull request by tobiasschweizer**
Use Knora UI modules to display values wherever possible and delete redundant local components.

This PR requires a new release of Knora UI wich will be available soon.

For development, the prelease builds are used.

closes #39 
closes #40 
closes #41

@SepidehAlassi I have refactored the templates so that they use the Knora UI modules wherever possible. Could you check if I broke anything? Not in the technical sense, but regarding the correct display of information. 

The best way to test this PR locally is:
- delete `yarn.lock`
- run `yarn install --prod=false` to install the dependencies from your build repos.

### CODE REVIEW

**Comment by SepidehAlassi** [comment]
[check the pull request for correct presentation of leoo resources](https://trello.com/c/WfIiQDAu/135-check-the-pull-request-for-correct-presentation-of-leoo-resources)

**Comment by SepidehAlassi** [comment]
[check the pull request for correct presentation of leoo resources](https://trello.com/c/WfIiQDAu/135-check-the-pull-request-for-correct-presentation-of-leoo-resources)

**Comment by SepidehAlassi** [comment]
[check the pull request for correct presentation of leoo resources](https://trello.com/c/WfIiQDAu/135-check-the-pull-request-for-correct-presentation-of-leoo-resources)

**Comment by SepidehAlassi** [comment]
[check the pull request for correct presentation of leoo resources](https://trello.com/c/WfIiQDAu/135-check-the-pull-request-for-correct-presentation-of-leoo-resources)

**Comment by SepidehAlassi** [comment]
@tobiasschweizer there is a problem with introductions. 
the links from landing page to introductions are not working anymore

**Comment by SepidehAlassi** [comment]
@tobiasschweizer Same problem with introduction sections is also true for list of abbreviations. It is not accessible from landing page

**Comment by tobiasschweizer** [comment]
@SepidehAlassi I will look at it and see where the problem is.

**Comment by tobiasschweizer** [comment]
The introduction and the sections are working for me. I am still using the data that is currently on the productive server. Do you get an error message?

**Comment by SepidehAlassi** [comment]
@tobiasschweizer I was not getting an error message, there was simply nothing loaded.
I tried it again right now with the new commit and it works! Can that be dependent on the core module update?!

**Comment by tobiasschweizer** [comment]
maybe. I made another build of the core module this morning and use it on this PR :-)

Is that PR ok now?

**Comment by SepidehAlassi** [comment]
yes, it is ok now as far as I see. I believe you can merge.

**Comment by tobiasschweizer** [comment]
Could you approve it ;-)

**Review by flavens — APPROVED** [review]

**Pull request merged**
