### PR TITLE
Render Math for list values in search results

### PR DESCRIPTION
**Pull request by tobiasschweizer**
This PR makes the search results component render math in list values. The list value comp. renders math by default, but accepts an input to disable rendering. This is useful to prevent rendering of all the elements of a big list.

math_list_values

list_val_result

### CODE REVIEW

**Comment by SepidehAlassi** [comment]
@tobiasschweizer this looks good to me. But how about the search for topics?

**Comment by tobiasschweizer** [comment]
> But how about the search for topics?

I am working on it :-) There will soon be a PR in Knora-ui

**Comment by tobiasschweizer** [comment]
@SepidehAlassi I am working on supporting lists in the GUI: https://github.com/dhlab-basel/Knora-ui/pull/170

**Review by SepidehAlassi — APPROVED** [review]
great!

**Pull request merged**
