### PR TITLE
lece

### PR DESCRIPTION
**Pull request by SepidehAlassi**
- displays Preface for Condorcet edition

- adapts side menu of introduction

### CODE REVIEW

**Comment by SepidehAlassi** [comment]
@tobiasschweizer you would need the new data to check this

**Comment by SepidehAlassi** [comment]
@tobiasschweizer Just a reminder: we need these changes for next release, can u please review this?

**Comment by tobiasschweizer** [comment]
@SepidehAlassi Ok, I will do it today. I have just finished the complete import, so I have the complete data.

**Review by tobiasschweizer — APPROVED** [review]
Nice work! 

With the new data, the person symbols appear where there are mentioned. That's great! I imagine that was a lot work in LaTeXML.

**Pull request merged**
