### PR TITLE
Introduction component

### LINKED ISSUE #60: "undefined" beolid when accessing the introduction
When accessing a section of the introduction, the beolid in the extended search is "undefined":

```sparql
PREFIX knora-api: <http://api.knora.org/ontology/knora-api/simple/v2#>
    PREFIX beol: <http://api.01.unibas.dasch.swiss/ontology/0801/beol/simple/v2#>

    CONSTRUCT {

        ?introSection knora-api:isMainResource true .
        ?superSection beol:hasSection ?introSection .

    } WHERE {

        ?introSection a beol:section .
      	?introSection a knora-api:Resource .
        ?introSection beol:beolIDs ?sectionId .

        beol:beolIDs knora-api:objectType xsd:string .
        ?sectionId a xsd:string .

        FILTER(?sectionId = "undefined")

        OPTIONAL {
            ?superSection beol:hasSection ?introSection .
        }

    }

    OFFSET 0
```

I think this is because `introduction.json` is loaded asynchronously and not ready yet when the search is sent:

screen shot 2018-10-31 at 9 31 38 am

The search should be sent once the `introduction.json` has been received (in the subscribe). Alternatively we can make `introduction.json` a TypeScript file so it is ready at compile time.

### PR DESCRIPTION
**Pull request by tobiasschweizer**
The JSON representing the introduction's structure was obtained asynchronously. This was unnecessary.

Also I could get rid of `NavigationEnd` (Subscription). Now the component only listens to changed parameters. Previously a reload was triggered also when the user opened the subelements of an active item.

fixes #60

### CODE REVIEW

**Review by kilchenmann — APPROVED** [review]
Great work

**Review by flavens — APPROVED** [review]

**Comment by tobiasschweizer** [comment]
@SepidehAlassi Does this work for you?

**Comment by SepidehAlassi** [comment]
@tobiasschweizer yes this works. However, the introduction component is currently specific to Goldbach volume. It should be made generic. you can go ahead and merge this. I will continue working on the introduction in "Condorcet" branch.

**Comment by tobiasschweizer** [comment]
@SepidehAlassi Yes, you are right. There is a JSON file that contains the specifics. I think we could just have several configuration files for different volumes. The rest of the logic should be generic.

**Pull request merged**
