### PR TITLE
Fix scroll in search results

### LINKED ISSUE #20: scroll event triggered immeditaley
scroll event is sometimes triggered immediately when a new result list is loaded

### LINKED ISSUE #27: refresh extended search
When hitting the browser's refresh button on an extended search, an error is reported: "OUPS ERROR: No Sparql string given for call of SearchService.doExtendedSearch"

I think this is because the previous search has not been saved in `extendedSearchParams`

### PR DESCRIPTION
**Pull request by kilchenmann**
resolves #20

### CODE REVIEW

**Review by tobiasschweizer — APPROVED** [review]

**Comment by tobiasschweizer** [comment]
looks great, thx

**Comment by tobiasschweizer** [comment]
it actually happened on `develop`:

bildschirmfoto 2018-10-24 um 09 41 05

since the scroll event triggered immediately, two searches were done at the same time, and the one with offset 1 was handled before the one with offset 0.

**Comment by kilchenmann** [comment]
?
This should be fixed with this PR?

**Comment by tobiasschweizer** [comment]
> This should be fixed with this PR?

Yes, it will :-)

**Comment by kilchenmann** [comment]
Then I will merge it... ;)

**Pull request merged**
