### PR TITLE
biblio template: display location

### PR DESCRIPTION
**Pull request by tobiasschweizer**
Location was not displayed correctly.

### CODE REVIEW

**Review by SepidehAlassi — CHANGES_REQUESTED** [review]
Location can contain a list of elements with different language attributes. Therefore there should be a for loop here.

**Comment by tobiasschweizer** [comment]
aha :-)  will do it!

**Comment by tobiasschweizer** [comment]
@SepidehAlassi I made it a loop.

Once https://github.com/dhlab-basel/Knora-ui/issues/127 we can filter for the user's preferred language.

**Review by SepidehAlassi — APPROVED** [review]

**Comment by SepidehAlassi** [comment]
@tobiasschweizer yes, we should implement language filtering at some point

**Pull request merged**
