### PR TITLE
Wip/bebb redirect

### PR DESCRIPTION
**Pull request by tobiasschweizer**
This PR provides a dedicated route for BEBB letters. 

The route `/bebb/title` redirects to the actual letter in BEOL. 

For example: `/bebb/1706-03-17_Hermann_Jacob-Scheuchzer_Johannes` will redirect to `/letter/letterIri`.

The current links to the BEBB wiki can be rewritten as follows: <https://www.ub.unibas.ch/bernoulli/index.php/1706-03-17_Hermann_Jacob-Scheuchzer_Johannes> -> <https://beol.dasch.swiss/bebb/1706-03-17_Hermann_Jacob-Scheuchzer_Johannes> so they remain functional also after the transfer of the data.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@SepidehAlassi If you have a little bit of time, could you have a look at this PR? Thanks!

**Comment by SepidehAlassi** [comment]
@tobiasschweizer I will do this first thing tomorrow afternoon after my presentation.

**Comment by tobiasschweizer** [comment]
Thanks!

Good luck!

**Review by SepidehAlassi — APPROVED** [review]
nice!

**Comment by tobiasschweizer** [comment]
thx!

**Pull request merged**
