### PR TITLE
Update Knora-ui modules to 7.3.0

### PR DESCRIPTION
**Pull request by tobiasschweizer**
@SepidehAlassi Could you please have a look if the GUI works for you?

### CODE REVIEW

**Comment by SepidehAlassi** [comment]
@tobiasschweizer  nope, I just found this problem:
There is a problem with displaying the text: 
Screenshot 2019-04-05 10 47 36

There is a problem with displaying the text
`<h1 _ngcontent-c33="" class="mat-card-title ng-star-inserted" mat-card-title="">Correspondance d\'Euler avec le marquis de Condorcet\n        </h1>`

The same text in beta server is:
`<h1 _ngcontent-c18="" class="mat-card-title ng-star-inserted" mat-card-title="">Correspondance d'Euler avec le marquis de Condorcet
        </h1>`

**Comment by tobiasschweizer** [comment]
I checked the data (the dump from a few days ago) on and it looks like this:

```
Correspondance d\\'Euler avec le marquis de Condorcet\\n        
```

Could you please check your data as well?

**Comment by tobiasschweizer** [comment]
@SepidehAlassi Could you check if your data looks as in https://github.com/dhlab-basel/beol/pull/136#issuecomment-480257172?

**Comment by tobiasschweizer** [comment]
@SepidehAlassi maybe it is related to https://github.com/dhlab-basel/Knora/pull/1296

**Comment by tobiasschweizer** [comment]
@SepidehAlassi https://github.com/dhlab-basel/Knora/pull/1296 has been merged and the problem should be fixed after reimport of the data.

**Comment by tobiasschweizer** [comment]
@SepidehAlassi Can this PR be merged?

**Comment by SepidehAlassi** [comment]
@tobiasschweizer sorry for the delay. I will check this asap. yes, it seems to be related to dhlab-basel/Knora#1296
I will check with new Knora changes.

**Review by SepidehAlassi — APPROVED** [review]
the new line problem is solved with new Knora changes! The rest of your changes look good!

**Pull request merged**
