### PR TITLE
Wip/upgrade app fixes

### PR DESCRIPTION
**Pull request by tobiasschweizer**
Uses DSP-JS lib and updates to Angular 9.

The following tasks are still open:
- https://dasch.myjetbrains.com/youtrack/issue/DSP-588
- https://dasch.myjetbrains.com/youtrack/issue/DSP-551
- https://dasch.myjetbrains.com/youtrack/issue/DSP-587
- https://dasch.myjetbrains.com/youtrack/issue/DSP-590
- https://dasch.myjetbrains.com/youtrack/issue/DSP-591

Once merged, a new release will be created and deployed on the test server.

### CODE REVIEW

**Review by flavens — COMMENTED** [review]
LGTM in general
I did not have access to the preface, list of abbreviations and introductions because I do not have the images. 
In the main landing page, I would change the names and links to dsp-api doc and dsp-ui npm page.

**Comment by tobiasschweizer** [comment]
@flavens I changed the search mode to "gravsearch" in https://github.com/dhlab-basel/beol/pull/168/commits/cdd3c27e8ea26fba307ce630868a474f52afab0d

**Comment by tobiasschweizer** [comment]
> In the main landing page, I would change the names and links to dsp-api doc and dsp-ui npm page.

True, I created https://dasch.myjetbrains.com/youtrack/issue/DSP-599 for that.

**Comment by tobiasschweizer** [comment]
@mdelez @flavens @SepidehAlassi I suggest we merge this PR asap to see if we can deploy the app on the test server. All remaining tasks are on youtrack.

**Review by flavens — APPROVED** [review]

**Pull request merged**
