### PR TITLE
DSP-1107 Add Editors

### PR DESCRIPTION
**Pull request by SepidehAlassi**
Resolves [DSP-1107](https://dasch.myjetbrains.com/youtrack/agiles/110-4/111-72?issue=DSP-1107)
Add editors to different editions.

### CODE REVIEW

**Review by flavens — COMMENTED** [review]
it looks good! however I would reduce the space between the editor names because it takes a lot of space and it is not reproduce the same layout as the above sections. I suggest something like:

letter.component.html
```
<div *ngIf="editors.length>0" class="editorSection">
                    <h4 class="subheading-2">
                        <strong>Edited by:</strong>
                    </h4>
                    <mat-list *ngFor="let editor of editors" class="editorList">
                        <mat-list-item class="editorItemList">
                        <span class="link"
                              (click)="showEditorsRes(editor.gnd)">{{editor.name}}</span>
                        </mat-list-item>
                    </mat-list>
                </div>
```

letter.component.scss
```
.editorSection {
  margin-bottom: 24px;
}

.editorList, .editorItemList {
  margin: 0 !important;
}

.editorItemList {
  min-height: 24px !important;
}
```

**Comment by SepidehAlassi** [comment]
@flavens Thanks for your review. I have fixed the CSS for list items and font size. Can I merge this now?

**Comment by flavens** [comment]
> @flavens Thanks for your review. I have fixed the CSS for list items and font size. Can I merge this now?

You have to request my review again.

**Review by flavens — APPROVED** [review]
it looks ok, just careful with the various font sizes: the main content is smaller than the title and the left column content, the notes are even smaller. I thought my page had a zooming problem.

**Pull request merged**
