### PR TITLE
mapping component 

### LINKED ISSUE #164: ark URLs are not resolved with angular templates
I have tried accessing a couple of letter resources of BEOL using ARK URLs, but they do not resolve correctly. The application only shows the letters using the general resource template and does not use the angular templates defined for representing each resource type.

Try:
ARK URL: http://ark.dasch.swiss/ark:/72163/1/0801/v5mma7PzTcOD8ZndsBBDVAq

of the resource
https://api.dasch.swiss/v2/resources/http:%2F%2Frdfh.ch%2F0801%2Fv5mma7PzTcOD8ZndsBBDVA

Since the general resource template dumps all properties of a resource without any styling, the result looks horrible.
It is particularly problematic when it comes to newton:letter and leibniz:letter resources, because the text of the letters is fetched and displayed using the components defined for these resource types.

### PR DESCRIPTION
**Pull request by SepidehAlassi**
added a mapping component for resources
the previous "resource" template to display all properties of a resource is changed to "simpleResource"
resolves https://github.com/dhlab-basel/beol/issues/164

### CODE REVIEW

**Comment by flavens** [comment]
@SepidehAlassi could you send us the BEOL data?

**Comment by SepidehAlassi** [comment]
@flavens you already have access to the data on the switch drive. I will email you the link again.

**Review by flavens — APPROVED** [review]
@SepidehAlassi it looks great to me. Just one thing: you should change the selector of the SimpleResourceComponent because it is the same as ResourceComponent and they should be unique..

**Comment by SepidehAlassi** [comment]
@flavens thanks for the review. I changed the selector. Anything else? or should I go ahead and merge?

**Comment by flavens** [comment]
> @flavens thanks for the review. I changed the selector. Anything else? or should I go ahead and merge?

nothing else. I think you can merge it

**Pull request merged**
