### PR TITLE
Meditationes webfonts

### PR DESCRIPTION
**Pull request by SepidehAlassi**
This pullrequest adds the icons for the svg files created by Cornelia for the Meditationes

### CODE REVIEW

**Comment by SepidehAlassi** [comment]
@tobiasschweizer Please try these icons in your data.

**Comment by tobiasschweizer** [comment]
@SepidehAlassi Thanks a lot for this PR!

I deployed this PR's version of the beol GUI on iml-leonhard. Does the XML source have to be changed? So far, special chars are replaced by combinations of characters.

**Comment by SepidehAlassi** [comment]
@tobiasschweizer in the xml files you have to replace the placeholders with the fonts. 
Ex: In the goldbach letter L065 the special character which was denoted in LaTeX as "\fxFk" is replaced with 
`<font fontType="icon-fxFk"/>`
Then in the mapping I have defined:
```
<mappingElement>
        <tag>
            <name>font</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
            <separatesWords>true</separatesWords>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/0801/beol#StandoffFontTag</classIri>
            <attributes>
                <attribute>
                    <attributeName>fontType</attributeName>
                    <namespace>noNamespace</namespace>
                    <propertyIri>http://www.knora.org/ontology/0801/beol#standoffFontType</propertyIri>
                </attribute>
            </attributes>
        </standoffClass> 
    </mappingElement>
```

In this way the webfont is considered in the html rendering of the letter content with the special character. 
I hope this helps you.

**Comment by tobiasschweizer** [comment]
I found this in the docs of MathJax: http://docs.mathjax.org/en/latest/font-support.html#adding-new-fonts:

> As mentioned, MathJax needs pre-generated font data to support a fonts. This font data can be generated using the MathJax development tools.

-> https://github.com/mathjax/MathJax-dev

**Pull request closed without merging**
