### PR TITLE
feature (BEBB): add directive to render link to HAN catalogue

### LINKED ISSUE #44: BEBB letter: link to catalogue
create a link to the catalogue of the university library using the system number

### PR DESCRIPTION
**Pull request by tobiasschweizer**
Add directive to display a link to the library catalogue.

closes #44

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@SepidehAlassi You can tests this with any BEBB letter. On the left side, there is a link to the catalogue.

catalogue

**Comment by SepidehAlassi** [comment]
General question: is having a separative directive necessary for this? Are you expecting the baseURI of ub to be changed at some point? Otherwise, SystemNumber could have been saved in the triplestore not as a text but as URI (baseUri+systemNumber) and could be displayed easily with ReadURIValue. The same as the ExternalLink property I just added to the bibliographical items in my previous PR.

**Comment by tobiasschweizer** [comment]
> Are you expecting the baseURI of ub to be changed at some point?

Yes, like this an adaption would be very easy to do. Also there is a language param in the URL that we could set according to the active language.

The directive is like a simple driver. We do the same thing with GNDs.

**Comment by tobiasschweizer** [comment]
> The same as the ExternalLink property I just added to the bibliographical items in my previous PR

When would you use an `ExternalLink`?

**Comment by SepidehAlassi** [comment]
> When would you use an `ExternalLink`?

BEZ is using external link, when the publication is also available online somewhere.

**Comment by tobiasschweizer** [comment]
> BEZ is using external link, when the publication is also available online somewhere.

I think in that case that's the right thing to to.

**Comment by SepidehAlassi** [comment]
> like this an adaption would be very easy to do.

For the case where there is one single URI to be adapted (Like GND is always referring to DNB and now the system number to the UB. ), it makes sense of course to have a directive, then you can just adapt the URI in the directive if necessary.

In the case of ExternalLink of publication that is not the case, as links are pointing to various websites.

**Comment by tobiasschweizer** [comment]
> In the case of ExternalLink of publication that is not the case, as links are pointing to various websites.

Yes, if you do not know the system behind it or it simply does not matter, you can just use the URL.

**Comment by SepidehAlassi** [comment]
hmm, now I am thinking maybe I should also make a directive for newton letters using their filename, then users can be directed to the letter on The Newton Project.
(in addition to fetching the text and displaying it in BEOL. )

**Comment by SepidehAlassi** [comment]
I will check this PR soon, no worries 😄

**Comment by tobiasschweizer** [comment]
> hmm, now I am thinking maybe I should also make a directive for newton letters using their filename, then users can be directed to the letter on Newton project.

I think if there is a consistent way to do this, this would be quite a flexible way to handle this. Otherwise the data would have to be changed.

**Comment by tobiasschweizer** [comment]
> I will check this PR soon, no worries 😄

No rush :-)

**Review by SepidehAlassi — APPROVED** [review]
this looks good, I also tested it with BEBB data, works like a charm 😄

**Comment by SepidehAlassi** [comment]
@tobiasschweizer half-related topic: do you think it might seem more user-friendly if the "_" occurrences are removed from "Title" property?

**Comment by tobiasschweizer** [comment]
>  do you think it might seem more user-friendly if the "_" occurrences are removed from "Title" property?

The title is like an id and is used in the URLs. At some point, we have to define rewrite rules to BEOL. Maybe there could be an internal ID like a beol-id and a visible title property.

**Comment by tobiasschweizer** [comment]
> this looks good, I also tested it with BEBB data, works like a charm

Thanks a lot for the review!

**Pull request merged**
