### PR TITLE
refactor (app): runtime config

### PR DESCRIPTION
**Pull request by tobiasschweizer**
Adaptions for runtime config (https://github.com/dhlab-basel/Knora-ui/pull/180)

`package.json` as to to be updated so it uses the new versions of knora-ui

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@SepidehAlassi We will integrate the new runtime config on this branch, so you can merge into the Newton branch once it is ready

**Comment by SepidehAlassi** [comment]
@tobiasschweizer That sounds good!

**Comment by tobiasschweizer** [comment]
@kilchenmann @subotic 

I updated the Knora-ui modules in 
https://github.com/dhlab-basel/beol/pull/118/commits/3fdbbe7431303814941b9c49786cc5aa61fd2998

Could you help me fix the test? There is a configuration problem:

> Failed: StaticInjectorError(DynamicTestModule)[InjectionToken KuiCoreConfigToken (knora.core.config)]: 
  StaticInjectorError(Platform: core)[InjectionToken KuiCoreConfigToken (knora.core.config)]: 
    NullInjectorError: No provider for InjectionToken KuiCoreConfigToken (knora.core.config)!

**Comment by tobiasschweizer** [comment]
in the specs, the following has to go into the config of providers:

```
providers: [
    { provide: KuiCoreConfigToken, useValue: KuiCoreConfig }
]
```

**Comment by tobiasschweizer** [comment]
@subotic @kilchenmann 

https://github.com/dhlab-basel/beol/pull/118/commits/5a00b38d4cf08feca69564349de340c155272a4e maybe fixes the issue. Could you please check if that is correct?

**Comment by tobiasschweizer** [comment]
@SepidehAlassi I hope this works now. We have to check tomorrow.

**Comment by SepidehAlassi** [comment]
@tobiasschweizer should I merge it to newton branch?

**Comment by tobiasschweizer** [comment]
Please wait until I checked this PR with Ivan and André tomorrow

On 21 Feb 2019, at 19:16, Sepideh Alassi <notifications@github.com<mailto:notifications@github.com>> wrote:


@tobiasschweizer<https://github.com/tobiasschweizer> should I merge it to newton branch?

**Comment by kilchenmann** [comment]
LGTM! @SepidehAlassi i think you can merge it into your newton branch...

**Comment by SepidehAlassi** [comment]
> i think you can merge it into your newton branch...

@kilchenmann will do, thanks!

**Comment by SepidehAlassi** [comment]
> LGTM! @SepidehAlassi i think you can merge it into your newton branch..

@kilchenmann I merged in newton branch, but it does not work for me! should I change something in configuration?

screenshot 2019-02-24 23 34 41

**Comment by kilchenmann** [comment]
I will have a look on it...right now I‘m on the way to basel

**Comment by kilchenmann** [comment]
@SepidehAlassi I can't reproduce your errors. It works fine on my computer... Perhaps we need more information what you have done? Btw I just took the branch `newton` and started the app with `ng s`.
How did you run it? To configure the app you have to use the following file now: `src/config/config.dev.json`. If you have to run it in productive mode `ng s --prod` you should have a `src/config/config.prod.json` file.

**Comment by SepidehAlassi** [comment]
@kilchenmann Ah sorry, I had to simply restart the whole application after the merge. It was too late last night, did not think of it. Just ran the app without restarting, sorry for the inconvenience. all works now!

**Comment by SepidehAlassi** [comment]
@kilchenmann @tobiasschweizer  are you going to merge this to develope?

**Comment by kilchenmann** [comment]
@SepidehAlassi But, you haven't merge this branch (`wip/config-runtime`) into your newton branch? There's no commit about it.

**Comment by SepidehAlassi** [comment]
@kilchenmann I have merged this branch into the newton branch locally to test if everything works. I have not commited/pushed this merge, because I believe it would be the best if you merge this branch into develop then I merge develop into newton branch. Don't you think?

**Comment by kilchenmann** [comment]
Yes it would be the best practice to merge from develop. This is always better. There was another opinion here in the office 🙊

**Review by kilchenmann — APPROVED** [review]

**Comment by SepidehAlassi** [comment]
> Yes it would be the best practice to merge from develop. This is always better. There was another opinion here in the office 🙊

good that we are all now in agreement. 😄

**Pull request merged**
